### ISSUE TITLE
Please delete 4.2.0 branch

### ISSUE THREAD

**Issue by ericonr** [epics-base/p4p#161]
The branch was merged in https://github.com/epics-base/p4p/pull/158

Its existence makes it impossible to download a tarball with the URL <https://github.com/epics-base/p4p/archive/4.2.0.tar.gz>, which instead simply returns the following text: `the given path has multiple possibilities: #<Git::Ref:0x00007f82c2f2eb20>, #<Git::Ref:0x00007f82c2f2d680>`

It is of course possible to specify the tag with `refs/tags/`, but there's no reason to require it :)

Reference: https://www.drupal.org/project/webform/issues/3264249

**Comment by mdavidsaver** [comment]
`refs/heads/4.2.0` has been removed.  @ericonr thanks for pointing this out.
